---
# This panelConfig is intended for use with Svg1. It differs from the main panelConfig
# in that it uses grafana suplied RandomWalk time-series. This is useful for demonstrating
# that the panel works with externally provided time-series. However as we have no say on
# the range of values, it's not that useful as a demonstrator of thresholds.
#------------------------------------------------------------------------------
# YAML Aliases to simplify maintenance

variableThresholdScalars:
  A_series:
    - {variableValuePattern: ".*", thresholdScalar: 0.5, cellIdPatternScope: [".*box.*"]}
  #environment:
  #  - {variableValuePattern: "prod", thresholdScalar: 0.5, cellIdPatternScope: [".*box.*"]}


anchorLinks:
  - link: &grafana-home
      url: "https://grafana.com/"
      params: "time"

#------------------------------------------------------------------------------
# Panel Config

gradientMode: "hue"
cellIdPreamble: "cell-"
cells: 
  drawio:
    link:
      url: "https://app.diagrams.net/?p=svgdata"
  docs:
    link:
      url: "https://github.com/andymchugh/andrewbmchugh-flow-panel/blob/main/README.md"
  inbox_depth:
    dataRef: "{EndpointUrl="opc.tcp://fr0-vsiaas-4629:48010", NodeId="ns=12;s=A350_T6_CN.CncAxisList.AX1.AxisData.aaCurr", Quality="The operation succeeded. StatusGood (0x0)", database="AI_CAD_AMI_RAW", host="fr0-vsiaas-5711", topic="AI/SP/CAD/OPCUA/data"
    label:
      separator: "cr"
      units: "none"
      decimalPoints: 0
    labelColor:
      thresholds:
        - {color: "green", level: 0}
        - {color: "orange", level: 50}
        - {color: "red", level: 100}
    link: *grafana-home
  db_transactions:
    dataRef: "B_series"
    label:
      separator: "cr"
      units: "ops"
      decimalPoints: 0
    fillColor:
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "orange", level: 50}
        - {color: "red", level: 100}
    link: *grafana-home
  start_rate:
    dataRef: "B_series"
    label:
      separator: "colon"
      units: "pps"
      decimalPoints: 0
    labelColor:
      thresholds:
        - {color: "green", level: 0}
        - {color: "orange", level: 50}
    link: *grafana-home
  active_workers:
    dataRef: "A_series"
    label:
      separator: "cr"
      units: "none"
      decimalPoints: 0
    labelColor:
      thresholds:
        - {color: "#888888", level: 0}
        - {color: "light-blue", level: 50}
    link: *grafana-home
